name: Lint Python code with Ruff & mypy

on:
  push:
    branches:
      - ci-test

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        vs-versions: [66]
        python-version: ['3.12']

    steps:
      - uses: actions/checkout@v4

      - uses: qoomon/actions--context@v2
        id: context
        with:
          workflow-context: lint, ${{ toJSON(matrix) }}, ${{ inputs.workflow-context }}

      - uses: tj-actions/branch-names@v8
        id: branch-names

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up VapourSynth ${{ matrix.vs-versions }}
        uses: ./.github/actions/setup-vapoursynth
        with:
          vapoursynth-version: ${{ matrix.vs-versions }}

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -r requirements.txt -r requirements-dev.txt

      - name: Running ruff
        run: uv run ruff check .

      - name: Running mypy on vstools
        run: uv run mypy vstools

      - name: Running mypy on vssource
        run: uv run mypy vssource

      - name: Running mypy on vskernels
        run: uv run mypy vskernels

      - name: Post webhook for failure
        if: failure()
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          embed-url: ${{ steps.context.outputs.job_log_url }}
          embed-title: "[${{ github.event.repository.name }}] ${{ steps.context.outputs.job }} failed on ${{ steps.branch-names.outputs.current_branch }}"
          username: "GitHub - ${{ github.repository }}"
          avatar-url: https://github.githubassets.com/favicons/favicon.png
