name: Lint Python code with Ruff

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        vs-versions: [70]
        vszip-versions: [5]
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up VapourSynth ${{ matrix.vs-versions }}
        uses: ./.github/actions/setup-vapoursynth
        with:
          vapoursynth-version: ${{ matrix.vs-versions }}

      - name: Set up vszip ${{ matrix.vszip-versions }}
        uses: ./.github/actions/setup-vszip
        with:
          vszip-version: ${{ matrix.vszip-versions }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Running ruff
        run: ruff check .

      - name: Running mypy on vstools
        run: mypy vstools
